config:
  dockerfile: .woloxci/Dockerfile
  project_name: wbooks

steps:
  lint:
    - ln -sfn /home/node/node_modules node_modules
    - yarn run lint
    - yarn run check-types

environment:
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
